#!/bin/bash

IP_ADDRESS=$(ip route get 1 | grep -E "([0-9]{1,3}\.){3}[0-9]{1,3}" | awk '{ print $7 }')

if [[ "${IP_ADDRESS}" != "" ]]; then
  echo "${IP_ADDRESS}"
  echo "${IP_ADDRESS}"
  echo ""
fi
