#!/bin/bash
# Based on http://openweathermap.org/current

API_KEY="51688a01d1ea694d5dcd40a090adf508"
LOCATION_FILE="/tmp/current_location.txt"

#COORDINATES="$(curl -s https://ipapi.co/json)"
COORDINATES="$(curl -s http://ip-api.com/json/)"
if jq -e . >/dev/null 2>&1 <<<"$COORDINATES"; then
    echo $COORDINATES > $LOCATION_FILE
fi


URGENT_LOWER=10
URGENT_HIGHER=35

ICON_SUNNY=""
ICON_CLOUDY=""
ICON_RAINY=""
ICON_STORM=""
ICON_SNOW=""
ICON_FOG=""

SYMBOL_CELSIUS="C"
#"℃"



#LATITUDE="$(cat $LOCATION_FILE | jq -r '.latitude')"
#LONGITUDE="$(cat $LOCATION_FILE | jq -r '.longitude')"
LATITUDE="$(cat $LOCATION_FILE | jq -r '.lat')"
LONGITUDE="$(cat $LOCATION_FILE | jq -r '.lon')"
WEATHER_URL="http://api.openweathermap.org/data/2.5/weather?lat=${LATITUDE}&lon=${LONGITUDE}&appid=${API_KEY}&units=metric"

WEATHER_INFO=$(wget -qO- "${WEATHER_URL}")
WEATHER_MAIN=$(echo "${WEATHER_INFO}" | grep -o -e '\"main\":\"[a-Z]*\"' | awk -F ':' '{print $2}' | tr -d '"')
WEATHER_TEMP=$(echo "${WEATHER_INFO}" | grep -o -e '\"temp\":\-\?[0-9]*' | awk -F ':' '{print $2}' | tr -d '"')
CITY="$(cat $LOCATION_FILE | jq -r '.city')"

if [[ "${WEATHER_MAIN}" = *Snow* ]]; then
  echo "${CITY} ${ICON_SNOW} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
  echo "${CITY} ${ICON_SNOW} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
  echo ""
elif [[ "${WEATHER_MAIN}" = *Rain* ]] || [[ "${WEATHER_MAIN}" = *Drizzle* ]]; then
  echo "${CITY} ${ICON_RAINY} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
  echo "${CITY} ${ICON_RAINY} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
  echo ""
elif [[ "${WEATHER_MAIN}" = *Cloud* ]]; then
  echo "${CITY} ${ICON_CLOUDY} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
  echo "${CITY} ${ICON_CLOUDY} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
  echo ""
elif [[ "${WEATHER_MAIN}" = *Clear* ]]; then
  echo "${CITY} ${ICON_SUNNY} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
  echo "${CITY} ${ICON_SUNNY} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
  echo ""
elif [[ "${WEATHER_MAIN}" = *Fog* ]] || [[ "${WEATHER_MAIN}" = *Mist* ]]; then
  echo "${CITY} ${ICON_FOG} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
  echo "${CITY} ${ICON_FOG} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
  echo ""
else
  echo "${CITY} ${WEATHER_MAIN} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
  echo "${CITY} ${WEATHER_MAIN} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
  echo ""
fi

if [[ "${WEATHER_TEMP}" -lt "${URGENT_LOWER}" ]] || [[ "${WEATHER_TEMP}" -gt "${URGENT_HIGHER}" ]]; then
  exit 33
fi
