# --- general -------------------------------------------------
set -g history-limit 50000        # bigger scrollback
set -sg escape-time 10            # no lag switching modes in vim
set -g display-time 2000          # status messages stay ~2s
set -g focus-events on            # let vim/nvim react to focus
setw -g aggressive-resize on      # resize to the smallest *active* client

# Start windows and panes at 1 instead of 0
set -g base-index 1               # windows start at 1, not 0
setw -g pane-base-index 1
set -g renumber-windows on        # close a window, indices tidy up

# Tell tmux that Ghostty (the outer terminal) supports extended keys
#set -as terminal-features 'xterm-256color:extkeys'
set -as terminal-features 'xterm*:extkeys'
set -g allow-passthrough on

# Turn on extended keys and use the CSI-u encoding Ghostty speaks
set -s extended-keys off # clipboard paste wasn't working with this
#set -s extended-keys-format csi-u # not needed



# --- mouse + copy mode ---------------------------------------
set -g mouse on                   # scroll, select, resize with mouse
#setw -g mode-keys vi              # vi keys in copy mode

# --- friendlier keybinds -------------------------------------
bind r source-file ~/.config/tmux/tmux.conf \; display "reloaded"
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"
bind h split-window -v -c "#{pane_current_path}"
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# select tab (ghostty will send these from Ctrl+..)
set -s user-keys[0] "\ez1"
set -s user-keys[1] "\ez2"
set -s user-keys[2] "\ez3"
set -s user-keys[3] "\ez4"
set -s user-keys[4] "\ez5"
set -s user-keys[5] "\ez6"
set -s user-keys[6] "\ez7"
set -s user-keys[7] "\ez8"
set -s user-keys[8] "\ez9"
set -s user-keys[9] "\ezs"

bind -n User0 select-window -t 1
bind -n User1 select-window -t 2
bind -n User2 select-window -t 3
bind -n User3 select-window -t 4
bind -n User4 select-window -t 5
bind -n User5 select-window -t 6
bind -n User6 select-window -t 7
bind -n User7 select-window -t 8
bind -n User8 select-window -t 9
bind -n User9 select-pane -L

bind -n C-n new-window
